server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  jwt:
    secret: ${JWT_SECRET_KEY}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka에서 서비스 자동 탐색
          lower-case-service-id: true  # 서비스 ID를 소문자로 변환
      routes:
        - id: user-service
          uri: lb://login-server # Eureka에서 login-server의 동적 주소를 찾음
          #uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/auth/**
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**